=== softwarepub/hermes/docs/source/plugins-schema.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "List of plugins",
  "uniqueItems": true,
  "minItems": 1,
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "name": {
        "type": "string",
        "description": "Name of the plugin"
      },
      "author": {
        "type": "string",
        "description": "Author of the plugin, usually a team or organization"
      },
      "description": {
        "type": "string",
        "description": "A short description of the plugin"
      },
      "steps": {
        "type": "array",
        "description": "Steps of the Hermes workflow targeted by this plugin",
        "items": {
          "type": "string",
          "uniqueItems": true,
          "enum": [
            "harvest",
            "process",
            "curate",
            "deposit",
            "postprocess"
          ]
        }
      },
      "harvested_files": {
        "type": "array",
        "description": "Names of files harvested by a harvest plugin",
        "items": {
          "type": "string",
          "uniqueItems": true
        }
      },
      "repository_url": {
        "type": "string",
        "description": "Link to the repository where users can find and inspect the source code of the plugin",
        "format": "uri"
      },
      "pypi_url": {
        "type": "string",
        "description": "Link to the project on PyPI",
        "format": "uri"
      },
      "builtin": {
        "type": "boolean",
        "description": "Whether this plugin is built into Hermes"
      }
    },
    "required": [
      "name",
      "author"
    ]
  }
}

=== softwarepub/hermes/docs/source/plugins/plugins.json
[
    {
        "name": "CITATION.cff Harvester",
        "description": "Harvest plugin for CITATION.cff files.",
        "author": "Hermes team",
        "steps": ["harvest"],
        "harvested_files": ["CITATION.cff"],
        "builtin": true
    },
    {
        "name": "codemeta.json Harvester",
        "description": "Harvest plugin for codemeta.json files.",
        "author": "Hermes team",
        "steps": ["harvest"],
        "harvested_files": ["codemeta.json"],
        "builtin": true
    },
    {
        "name": "'file_exists' Harvester",
        "description": "Harvest plugin that figures out whether certain frequently used files (README, LICENSE, ...) exist. Custom search patterns for other types of files can be configured.",
        "author": "Hermes team",
        "steps": ["harvest"],
        "harvested_files": [
            "readme",
            "license"
        ],
        "builtin": true
    },
    {
        "name": "hermes-plugin-git",
        "description": "Harvest plugin for Git repository metadata.",
        "author": "Hermes team",
        "steps": ["harvest"],
        "repository_url": "https://github.com/softwarepub/hermes-plugin-git"
    },
    {
        "name": "hermes-plugin-python",
        "description": "Harvest plugin for .toml files.",
        "author": "Hermes team",
        "steps": ["harvest"],
        "harvested_files": ["pyproject.toml"],
        "repository_url": "https://github.com/softwarepub/hermes-plugin-python",
        "pypi_url": "https://pypi.org/project/hermes-plugin-python/"
    },
    {
        "name": "Merge",
        "description": "Process plugin for basic merging of metadata.",
        "author": "Hermes team",
        "steps": ["process"],
        "builtin": true
    },
    {
        "name": "Curate",
        "description": "Curation plugin for no-check acceptance of the metadata.",
        "author": "Hermes team",
        "steps": ["curate"],
        "builtin": true
    },
    {
        "name": "Invenio Deposit",
        "description": "Deposit plugin for Invenio-based platforms.",
        "author": "Hermes team",
        "steps": ["deposit"],
        "builtin": true
    },
    {
        "name": "Invenio RDM Deposit",
        "description": "Deposit plugin for Invenio RDM-based platforms such as Zenodo.",
        "author": "Hermes team",
        "steps": ["deposit"],
        "builtin": true
    },
    {
        "name": "Rodare Deposit",
        "description": "Deposit plugin for the Rodare publication platform at HZDR.",
        "author": "Hermes team",
        "steps": ["deposit"],
        "builtin": true
    },
    {
        "name": "Invenio Postprocess",
        "author": "Hermes team",
        "steps": ["postprocess"],
        "builtin": true
    },
    {
        "name": "Invenio RDM Postprocess",
        "author": "Hermes team",
        "steps": ["postprocess"],
        "builtin": true
    }
]

=== softwarepub/hermes/docs/source/plugins.json
[
    {
        "name": "CITATION.cff",
        "description": "Harvest plugin for CITATION.cff files.",
        "author": "Hermes team",
        "builtin": true
    },
    {
        "name": "codemeta.json",
        "description": "Harvest plugin for codemeta.json files.",
        "author": "Hermes team",
        "builtin": true
    },
    {
        "name": "hermes-plugin-git",
        "description": "Harvest plugin for Git repository metadata.",
        "author": "Hermes team",
        "repository_url": "https://github.com/softwarepub/hermes-plugin-git"
    },
    {
        "name": "hermes-plugin-python",
        "description": "Harvest plugin for .toml files.",
        "author": "Hermes team",
        "repository_url": "https://github.com/softwarepub/hermes-plugin-python",
        "pypi_url": "https://pypi.org/project/hermes-plugin-python/"
    },
    {
        "name": "merge",
        "description": "Process plugin for basic merging of metadata.",
        "author": "Hermes team",
        "builtin": true
    },
    {
        "name": "Invenio Deposit",
        "description": "Deposit plugin for Invenio-based platforms.",
        "author": "Hermes team",
        "builtin": true
    },
    {
        "name": "Invenio RDM Deposit",
        "description": "Deposit plugin for Invenio RDM-based platforms such as Zenodo.",
        "author": "Hermes team",
        "builtin": true
    },
    {
        "name": "Rodare Deposit",
        "description": "Deposit plugin for the Rodare publication platform at HZDR.",
        "author": "Hermes team",
        "builtin": true
    },
    {
        "name": "Invenio Postprocess",
        "author": "Hermes team",
        "builtin": true
    },
    {
        "name": "Invenio RDM Postprocess",
        "author": "Hermes team",
        "builtin": true
    }
]
